name: Build, code quality, tests

on:
  push:
    branches:
      - main
    paths:
      - 'package.json' # only release when version changes
  workflow_dispatch: # allow manual triggering of action

env:
  APP_CENTER_TOKEN: ${{ secrets.APP_CENTER_TOKEN  }}
  APP_NAME: ${{ 'TMP-ORG/TMP'  }}
  TESTING_GROUP: ${{  'Collaborators'  }}
  UPLOAD_FILE: ${{ 'android/app/build/outputs/apk/release/app-release.apk'  }}

jobs:
  build:
    name: Start Build âš’ï¸
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: SetUp JDK 11 âš™ï¸
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install dependencies ğŸ”—
        run: yarn install
      - name: Build android âš’ï¸
        run: cd android && ./gradlew assembleRelease
      - name: Upload artefact to App Center ğŸš€
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: ${{ env.APP_NAME }}
          token: ${{ env.APP_CENTER_TOKEN }}
          group: ${{ env.TESTING_GROUP }}
          file: ${{ env.UPLOAD_FILE }}
          notifyTesters: true
          debug: false
